### ISSUE TITLE
Instrument popular HPC libraries

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/Extrae.jl#2]
We should instrument the following popular libraries:
- [x] Distributed
- [ ] Base.Threads
- [ ] MPI.jl
- [ ] Dagger.jl
- [ ] CUDA.jl
- [ ] oneAPI.jl
- [ ] AMDGPU.jl

**Comment by exaexa** [comment]
I'd target mostly Distributed and maybe Dagger. CUDA/AMDGPU already do a lot of ugly stuff with the source and I expect complications. For our usecases we might add DistributedData.jl

**Comment by mofeing** [comment]
> I'd target mostly Distributed and maybe Dagger. CUDA/AMDGPU already do a lot of ugly stuff with the source and I expect complications.

In the case of CUDA/AMDGPU, my idea is to instrumentalize kernel launch and data movements, which Extrae should already be capable of detect.

**Comment by clasqui** [comment]
For the PerMedCoE use case, I agree with targeting Distributed and its variants.  I would also try the Base.Threads, as it seems to be the basic shared memory model in Julia.
